### ISSUE TITLE
New epubjs-reader not working with zipped .epub files

### ISSUE THREAD

**Issue by ledandmetallica** [futurepress/epubjs-reader#10]
I was trying to use the new epubjs version because it fixes the IOS issues but it is not working with zipped epub files as it used to. if I try with an unziped version of the epub in a folder it picks up inmediately. I can help to fix this but I need some insight on the unzipping part. @fchasen

**Comment by ledandmetallica** [comment]
I found this error debugging the js:
error = TypeError: this.zip.loadAsync is not a function at Archive.open (****/epub.js:15903:20)

**Comment by fchasen** [comment]
Have you included [JSZip](https://stuk.github.io/jszip/)?

**Comment by ledandmetallica** [comment]
I used your index.html and it has it AFAIK 
<script src="js/libs/zip.min.js"></script>

**Comment by ledandmetallica** [comment]
ok. It works now. I had to download the new version of JSZip and include that one.The one included in the example is not working tho. Thanks for the help

**Comment by fchasen** [comment]
Updated to jszip@3.1.5 in the repo
