### ISSUE TITLE
Missing metadata parsed

### ISSUE THREAD

**Issue by HackHarry** [futurepress/epubjs-reader#52]
If an epub book has more than one creator, I only get the first creator throw `book.packaging.metadata `.
My epubjs's version is 0.3.88
For example:
![image](https://user-images.githubusercontent.com/27217566/116839481-2590e980-ac05-11eb-987a-e9d65912a51d.png)
![image](https://user-images.githubusercontent.com/27217566/116839514-3e999a80-ac05-11eb-81df-cad484318e6b.png)

**Comment by SebastianKohler** [comment]
Here's my solution: https://github.com/futurepress/epub.js/issues/950#issuecomment-1031800157
